### ISSUE TITLE
Improvement: expose parse library

### ISSUE THREAD

**Issue by asgoth** [mixu/amdetective#6]
Hi,

Next to pipe-iterators, this is the second library I've found very useful.

I would like to search require.configs in files. Therefor, I need to use the `findConfig` function from `lib/parse.js`.

Now at the moment, I just used:

    var parse = require('amdetective/lib/parse');
    // parses the first require.config found
    var conf = parse.findConfig(contents);

But I'm a bit hesitant to use internal libraries. Maybe it is possible to export `parse.js`, e.g.

    module.exports.parse = parse;

If you want, I can do a pull request for it.

**Comment by mixu** [comment]
sounds good - if you can create a PR I'll take look tomorrow!

**Comment by mixu** [comment]
published a
